webtalk_init -webtalk_dir F:/Documents/University/year_4/system_design/Hardware/AES_basic/AES_Hardware/AES_basic/AES_basic.sim/sim_1/behav/xsim/xsim.dir/tb_shiftrows_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar 25 15:20:31 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212681853_0_0_329" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1b067957-0e4a-4de5-a05b-5e16f9175fb0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2b253df0dc5c41f0b2a60f24c6bc0fb6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "17" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2794 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "235 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6848_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2185811073 -regid "212681853_0_0_329" -xml F:/Documents/University/year_4/system_design/Hardware/AES_basic/AES_Hardware/AES_basic/AES_basic.sim/sim_1/behav/xsim/xsim.dir/tb_shiftrows_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/Documents/University/year_4/system_design/Hardware/AES_basic/AES_Hardware/AES_basic/AES_basic.sim/sim_1/behav/xsim/xsim.dir/tb_shiftrows_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/Documents/University/year_4/system_design/Hardware/AES_basic/AES_Hardware/AES_basic/AES_basic.sim/sim_1/behav/xsim/xsim.dir/tb_shiftrows_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
