@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Mar 25 15:36:43 +0000 2025
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_aes_top_behav -key {Behavioral:sim_1:Functional:tb_aes_top} -tclbatch tb_aes_top.tcl -view F:/Documents/University/year_4/system_design/Hardware/AES_basic/AES_Hardware/AES_basic/tb_aes_top_behav.wcfg -log simulate.log"
call xsim  tb_aes_top_behav -key {Behavioral:sim_1:Functional:tb_aes_top} -tclbatch tb_aes_top.tcl -view F:/Documents/University/year_4/system_design/Hardware/AES_basic/AES_Hardware/AES_basic/tb_aes_top_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
